packaging_format = 2

id = "collectiveaccess"
name = "CollectiveAccess"
description.en = "Cataloguing and data/media management application"
description.fr = "Cataloguing and data/media management application "

version = "1.7.17~ynh1"

maintainers = ["johndoe"]

[upstream]
license = "GPL-3.0-only"
website = "https://collectiveaccess.org/"
admindoc = "https://manual.collectiveaccess.org"
code = "https://github.com/collectiveaccess/providence"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/collectiveaccess/providence/archive/refs/tags/1.7.17.tar.gz"
        sha256 = "1eba6e5156411c3e0428fed55e4609942a35585bb647d7f5c28743ad8a7c0095"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = " php7.4-cli php7.4-gd php7.4-curl php7.4-mysqlnd php7.4-zip php7.4-fileinfo php7.4-opcache php7.4-xml php7.4-mbstring"

    [resources.database]
    type = "mysql"
