#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

chown -R $app:www-data "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create a dedicated PHP-FPM config using the conf/php-fpm.conf or conf/extra_php-fpm.conf
ynh_add_fpm_config --usage=low --footprint=low

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_add_nginx_config

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

# Create a dedicated Fail2Ban config
ynh_add_fail2ban_config --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1


mv $install_dir/setup.php.dist $install_dir/setup.php
ynh_replace_string --match_string=my_database_user --replace_string=$db_user --target_file=$install_dir/setup.php
ynh_replace_string --match_string=my_database_password --replace_string=$db_pwd --target_file=$install_dir/setup.php
ynh_replace_string --match_string=name_of_my_database --replace_string=$db_name --target_file=$install_dir/setup.php

#ynh_add_config --template="../conf/setup.php.dist" --destination="$install_dir/setup.php"

chmod 400 "$install_dir/setup.php"
chown $app:$app "$install_dir/setup.php"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
